### ISSUE TITLE
Inspection Settings Broken within CLIQZ Browser

### ISSUE THREAD

**Issue by stefanie-cliqz** [cliqz-oss/browser-f#93]
Hindering our ability to troubleshoot internally :/
https://cloud.githubusercontent.com/assets/7079226/9628353/8eb02120-516a-11e5-8ee0-12ddc18e58f8.png

experienced by @elyse-cliqz and @dominiks-cliqz, see https://github.com/cliqz/bug-tracker/issues/775

**Comment by chrmod** [comment]
looks like translation issue that was solved quite some time ago.

**Comment by stefanie-cliqz** [comment]
@roberto-cliqz would you please try to reproduce and confirm it's still an issue? Thanks!

**Comment by roberto-cliqz** [comment]
I tried to reproduce the bug, but everything worked fine. IMO it's not an issue anymore.

**Comment by stefanie-cliqz** [comment]
Great, thanks, Roberto. Closing this issue.
